-d /home/maddog/Documentos/Verilog/DSD/FlipFlopD/impl/gwsynthesis/FlipFlopD.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cfg /home/maddog/Documentos/Verilog/DSD/FlipFlopD/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
